---
- ansible.builtin.include_role:
    name: apt-key
    apply: { tags: [ always ] }
  vars:
    source: "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
    name: "{{ microsoft_edge_apt_name }}"
    keyname: "{{ microsoft_edge_apt_key_name }}"
    url: "{{ microsoft_edge_apt_key_url }}"
    dearmor: "{{ microsoft_edge_apt_key_dearmor }}"
  tags:
    - apt-key

- name: Install microsoft edge
  become: yes
  ansible.builtin.apt: pkg="{{ microsoft_edge_apt_pkg }}" state=present cache_valid_time=3600

- name: Update dock pinned apps
  ansible.builtin.include_role: name=pin-to-dock

