---
- name: Ubuntu Desktop
  hosts: "{{ hosts | default('all') }}"
  vars:
    # see group_vars/all.yml
  roles:
    - { role: kernel, tags: [ kernel ] }
    - { role: common, tags: [ common ] }
    - { role: sshd, tags: [ ssh ] }
    - { role: asus, tags: [ asus, oem ] }
    - { role: dell, tags: [ dell, oem ] }
    - { role: gnome, tags: [ gnome ] }
    - { role: firefox, tags: [ firefox ] }
    - { role: microsoft-edge, tags: [ edge ] }
    - { role: vscode, tags: [ code ] }
    - { role: github-cli, tags: [ github, git ] }
    - { role: spotify, tags: [ spotify, media ] }
    - { role: smplayer, tags: [ smplayer, media ] }
    - { role: fusuma, tags: [ fusuma ] }
    - { role: flatpak, tags: [ flatpak ] }
    - { role: steam, tags: [ steam ] }
    - { role: ms-teams, tags: [ teams ] }
