---
- name: Ubuntu Desktop
  hosts: "{{ hosts | default('all') }}"
  vars:
    # see group_vars/all.yml
  roles:
    # os essentials
    - { role: kernel, tags: [ kernel, os ] }
    - { role: common, tags: [ common, os ] }
    - { role: sshd, tags: [ ssh, os ] }
    - { role: graphics, tags: [ graphics, os ] }
    - { role: flatpak, tags: [ flatpak, os ] }
    # manufacturer specific
    - { role: asus, tags: [ asus, oem ] }
    - { role: dell, tags: [ dell, oem ] }
    # desktop common
    - { role: gnome, tags: [ gnome, desktop ] }
    - { role: firefox, tags: [ firefox, desktop ] }
    - { role: microsoft-edge, tags: [ edge, desktop ] }
    - { role: vscode, tags: [ code, desktop ] }
    - { role: git, tags: [ git, desktop ] }
    - { role: github-cli, tags: [ github, git, desktop ] }
    - { role: fusuma, tags: [ fusuma, desktop ] }
    - { role: ms-teams, tags: [ teams, desktop ] }
    # virtualization
    - { role: libvirt, tags: [ libvirt, virtualization ] }
    - { role: vagrant, tags: [ vagrant, virtualization ] }
    # media
    - { role: spotify, tags: [ spotify, media ] }
    - { role: smplayer, tags: [ smplayer, media ] }
    - { role: steam, tags: [ steam, media ] }
