---
- ansible.builtin.tempfile: state=file
  check_mode: no
  register: apt_key_temp_key
  changed_when: false

- name: Download temp apt key {{ keyname }}
  ansible.builtin.shell:
    cmd: |-
      set -e
      if [ "{{ dearmor | default(False) }}" = "True" ]; then
        curl -fsSL -o- '{{ url }}' | gpg --dearmor -o '{{ apt_key_temp_key.path }}' --yes
      else
        curl -fsSL -o'{{ apt_key_temp_key.path }}' '{{ url }}'
      fi
  changed_when: false

- ansible.builtin.set_fact:
    apt_key_key: "{{ apt_key_keyring_path }}/{{ keyname }}"
    apt_key_source: |-
      {{ source
          | regex_replace('([ \t]+[a-z]+://)', ' [signed-by={{ apt_key_key }}]\1')
          | replace('] [signed-by=', ' signed-by=')
      }}

- ansible.builtin.set_fact:
    apt_key_source: "{{ apt_key_source | replace('{{ apt_key_key }}', apt_key_key) }}"

- name: Add apt key {{ keyname }}
  ansible.builtin.copy:
    src: "{{ apt_key_temp_key.path }}"
    dest: "{{ apt_key_key }}"
    mode: 0644
  become: yes

- name: Delete temp apt key {{ keyname }}
  ansible.builtin.file: path="{{ apt_key_temp_key.path }}" state=absent
  changed_when: false

- name: Create apt source {{ name }}
  ansible.builtin.copy:
    dest: "/etc/apt/sources.list.d/{{ name }}.list"
    content: "{{ apt_key_source }}\n"
    mode: 0644
  become: yes
  register: apt_source_copy

- name: Update apt cache
  ansible.builtin.shell: apt-get update -qqy
  args: { warn: no }
  become: yes
  changed_when: apt_source_copy.changed
