---
- ansible.builtin.include_role:
    name: apt-key
    apply: { tags: [ always ] }
  vars:
    source: "deb https://apt.releases.hashicorp.com jammy main"
    name: "{{ vagrant_apt_name }}"
    keyname: "{{ vagrant_apt_key_name }}"
    url: "{{ vagrant_apt_key_url }}"
    dearmor: "{{ vagrant_apt_key_dearmor }}"
  tags:
    - apt-key

- name: Install vagrant and plugin dependencies
  become: yes
  ansible.builtin.apt:
    cache_valid_time: 3600
    state: present
    pkg:
    - "{{ vagrant_apt_pkg }}"
    - build-essential
    - libvirt-dev
    - ruby-libvirt
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install vagrant plugins
  check_mode: no
  args: { executable: /bin/bash }
  ansible.builtin.shell: |-
    set -e
    val=$(vagrant plugin list | awk '$1 == "{{ item }}" { print $1 }')
    [[ "$val" == "" ]] || exit 0
    echo "ansible_changed=yes"
    [[ "{{ ansible_check_mode }}" != "True" ]] || exit 0
    vagrant plugin install "{{ item }}"
  with_items:
    - vagrant-cachier
    - vagrant-disksize
    - vagrant-env
    - vagrant-libvirt
    - vagrant-vbguest
  register: res
  changed_when: res.stdout is search("ansible_changed=yes")
