---
- ansible.builtin.include_role: name=apt-key
  vars:
    source: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    name: "{{ vscode_apt_name }}"
    keyname: "{{ vscode_apt_key_name }}"
    url: "{{ vscode_apt_key_url }}"
    dearmor: "{{ vscode_apt_key_dearmor }}"

- name: Install vscode
  become: yes
  ansible.builtin.apt: pkg="{{ vscode_apt_pkg }}" state=present cache_valid_time=3600

- name: Update dock pinned apps
  ansible.builtin.include_role: name=pin-to-dock

