---
- name: Set system vendor fact
  ansible.builtin.set_fact:
    sys_vendor: "{{ lookup('file', '/sys/devices/virtual/dmi/id/sys_vendor') }}"

- name: Execute tasks for Asus devices
  ansible.builtin.include_tasks: oem.yml
  when: (sys_vendor | lower) is search("asus") or asus_force_role_enabled
