---
- name: Install fusuma dependencies
  become: yes
  ansible.builtin.apt:
    cache_valid_time: 3600
    pkg:
      - libinput-tools
      - ruby
      - xdotool

- name: Detect latest version of fusuma
  check_mode: no
  ansible.builtin.shell: gem list --quiet --remote fusuma | awk '$1 == "fusuma" { print $2 }' | sed -E 's/[()]//g'
  register: fusuma_version
  changed_when: false

- name: Install fusuma
  check_mode: no
  become: yes
  args: { executable: /bin/bash }
  ansible.builtin.shell: |-
    set -e
    version=$(gem list --quiet --local fusuma | awk '$1 == "fusuma" { print $2 }' | sed -E 's/[()]//g')
    [[ "$version" != "{{ fusuma_version.stdout }}" ]] || exit 0
    echo "ansible_changed=yes"
    [[ "{{ ansible_check_mode }}" != "True" ]] || exit 0
    gem install fusuma
  register: res
  changed_when: res.stdout is search("ansible_changed=yes")

- name: Copy fusuma sudoers file
  become: yes
  ansible.builtin.copy:
    src: sudoers
    dest: /etc/sudoers.d/fusuma-setgid
    mode: 0440

- name: Copy fusuma-setgid wrapper
  become: yes
  ansible.builtin.copy:
    src: fusuma-setgid
    dest: /usr/local/bin/fusuma-setgid
    mode: 0755

- name: Copy fusuma config
  ansible.builtin.copy:
    src: config/
    dest: "{{ ansible_env.HOME }}/.config/"
    directory_mode: 0700
    mode: 0600
