---
gnome_terminal_default_profile_id: ':b1dcc9dd-5262-4d8d-a863-c897e6d979b9'
gnome_terminal_default_profile_background_color: "'rgb(0,0,0)'"
gnome_terminal_default_profile_background_transparency_percent: '10'
gnome_terminal_default_profile_cursor_shape: "'ibeam'"
gnome_terminal_default_profile_default_size_columns: '120'
gnome_terminal_default_profile_default_size_rows: '36'
gnome_terminal_default_profile_foreground_color: "'rgb(255,255,255)'"
gnome_terminal_default_profile_palette: "['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,209,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']"
gnome_terminal_default_profile_use_theme_colors: 'false'
gnome_terminal_default_profile_visible_name: "'Default'"
gnome_terminal_legacy_menu_accelerator_enabled: 'false'

gnome_terminal_defaults:
  default_profile:
    namespace: "/org/gnome/terminal/legacy/profiles:/{{ gnome_terminal_default_profile_id }}"
    settings:
      background-color: "{{ gnome_terminal_default_profile_background_color }}"
      background-transparency-percent: "{{ gnome_terminal_default_profile_background_transparency_percent }}"
      cursor-shape: "{{ gnome_terminal_default_profile_cursor_shape }}"
      default-size-columns: "{{ gnome_terminal_default_profile_default_size_columns }}"
      default-size-rows: "{{ gnome_terminal_default_profile_default_size_rows }}"
      foreground-color: "{{ gnome_terminal_default_profile_foreground_color }}"
      palette: "{{ gnome_terminal_default_profile_palette }}"
      use-theme-colors: "{{ gnome_terminal_default_profile_use_theme_colors }}"
      visible-name: "{{ gnome_terminal_default_profile_visible_name }}"
  legacy:
    namespace: /org/gnome/terminal/legacy
    settings:
      menu-accelerator-enabled: "{{ gnome_terminal_legacy_menu_accelerator_enabled }}"
