---
- name: Add cappelikan ppa
  ansible.builtin.include_role:
    name: apt-key
    apply: { tags: [ always ] }
  vars:
    source: |-
      deb https://ppa.launchpadcontent.net/cappelikan/ppa/ubuntu/ {{ ansible_distribution_release }} main
      # deb-src https://ppa.launchpadcontent.net/cappelikan/ppa/ubuntu/ {{ ansible_distribution_release }} main
    name: cappelikan-ubuntu-mainline
    keyname: cappelikan-ppa.gpg
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3ae27527713d2479dcaffd58a89d7c1b2f76304d
    dearmor: yes
  tags:
    - apt-key

- name: Install mainline package
  become: yes
  ansible.builtin.apt: pkg=mainline state=present cache_valid_time=3600

- name: "Install kernel {{ kernel_mainline_version }}"
  check_mode: no
  become: yes
  args: { executable: /bin/bash }
  ansible.builtin.shell: |-
    set -e
    if ! ( mainline --list-installed \
        | awk '$0 ~ "Found installed" { print $3 }' \
        | egrep -q "^$(echo '{{ kernel_mainline_version }}' | sed 's/\./\\./g')\\b" ) \
    ; then
      echo "ansible_changed=yes"
      [[ "{{ ansible_check_mode }}" != "True" ]] || exit 0
      mainline --install '{{ kernel_mainline_version }}'
    fi
  register: install_kernel
  changed_when: install_kernel.stdout is search("ansible_changed=yes")
