---
- name: Install flatpak extensions
  become: yes
  ansible.builtin.apt:
    cache_valid_time: 3600
    state: present
    pkg:
      - flatpak
      - flatpak-builder
      - gnome-software-plugin-flatpak

- name: Add flathub
  check_mode: no
  become: yes
  args: { executable: /bin/bash }
  ansible.builtin.shell: |-
    set -e
    ! ( flatpak remotes --columns=name | grep -q flathub ) || exit 0
    echo "ansible_changed=yes"
    [[ "{{ ansible_check_mode }}" != "True" ]] || exit 0
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  register: res
  changed_when: res.stdout is search("ansible_changed=yes")
