---
- name: Install nautilus extensions
  become: yes
  ansible.builtin.apt:
    cache_valid_time: 3600
    state: present
    pkg:
      - nautilus-admin
      - nautilus-gtkhash

- name: Map nautilus settings
  ansible.builtin.set_fact:
    gnome_nautilus_items: |
      {{ gnome_nautilus_items | default([]) + [{
        'namespace': item.key,
        'settings': item.value | dict2items,
      }] }}
  with_items: "{{ gnome_nautilus_defaults | combine(gnome_nautilus | default({}), recursive=true) | dict2items }}"

- name: Configure nautilus
  check_mode: no
  args: { executable: /bin/bash }
  ansible.builtin.shell: |-
    set -e
    key="{{ item.0.namespace }}/{{ item.1.key }}"
    val=$(dconf read "$key")
    [[ "$val" != "{{ item.1.value }}" ]] || exit 0
    echo "ansible_changed=yes"
    [[ "{{ ansible_check_mode }}" != "True" ]] || exit 0
    dconf write "$key" "{{ item.1.value }}"
  notify:
    - reload gnome-shell
  with_subelements:
    - "{{ gnome_nautilus_items }}"
    - settings
  register: res
  changed_when: res.stdout is search("ansible_changed=yes")
