---
- name: Install gnome tweaks
  become: yes
  ansible.builtin.apt: pkg=gnome-tweaks state=present cache_valid_time=3600

- name: Map tweaks
  ansible.builtin.set_fact:
    gnome_tweaks_items: |
      {{ gnome_tweaks_items | default([]) + [{
        'namespace': item.value.namespace,
        'settings': item.value.settings | dict2items,
      }] }}
  with_items: "{{ gnome_tweaks_defaults | combine(gnome_tweaks | default({}), recursive=true) | dict2items }}"

- name: Configure tweaks
  check_mode: no
  args: { executable: /bin/bash }
  ansible.builtin.shell: |-
    set -e
    key="{{ item.0.namespace }}/{{ item.1.key }}"
    val=$(dconf read "$key")
    [[ "$val" != "{{ item.1.value }}" ]] || exit 0
    echo "ansible_changed=yes"
    [[ "{{ ansible_check_mode }}" != "True" ]] || exit 0
    dconf write "$key" "{{ item.1.value }}"
  notify:
    - reload gnome-shell
  with_subelements:
    - "{{ gnome_tweaks_items }}"
    - settings
  register: res
  changed_when: res.stdout is search("ansible_changed=yes")
