---
- name: Install git
  become: yes
  ansible.builtin.apt: pkg=git state=present cache_valid_time=3600

- name: git config
  check_mode: no
  args: { executable: /bin/bash }
  ansible.builtin.shell: |-
    set -e
    val=$(git config --global --get '{{ item.key }}')
    [[ "$val" != '{{ item.value }}' ]] || exit 0
    echo "ansible_changed=yes"
    [[ "{{ ansible_check_mode }}" != "True" ]] || exit 0
    git config --global '{{ item.key }}' '{{ item.value }}'
  with_items: "{{ git_config_defaults | combine(git_config | default({}), recursive=true) | dict2items }}"
  register: res
  changed_when: res.stdout is search("ansible_changed=yes")
