---
- name: Copy discord updater file
  become: yes
  ansible.builtin.copy:
    src: discord-updater
    dest: /usr/local/bin/discord-updater
    mode: 0755

- name: Install discord
  check_mode: no
  become: yes
  args: { executable: /bin/bash }
  ansible.builtin.shell: |-
    set -e
    if [[ ! -f /usr/local/bin/discord-updater ]]; then
      echo "update required: yes"
      exit 0
    fi
    if [[ "{{ ansible_check_mode }}" == "True" ]]; then
      /usr/local/bin/discord-updater --dry-run
    else
      /usr/local/bin/discord-updater
    fi
  register: res
  changed_when: "res.stdout is search('update required: yes')"

- name: Update dock pinned apps
  ansible.builtin.include_role: name=pin-to-dock
