---
- ansible.builtin.include_role:
    name: apt-key
    apply: { tags: [ always ] }
  vars:
    source: "deb [arch=amd64] https://cli.github.com/packages stable main"
    name: "{{ github_cli_apt_name }}"
    keyname: "{{ github_cli_apt_key_name }}"
    url: "{{ github_cli_apt_key_url }}"
    dearmor: "{{ github_cli_apt_key_dearmor }}"
  tags:
    - apt-key

- name: Install github-cli
  become: yes
  ansible.builtin.apt: pkg="{{ github_cli_apt_pkg }}" state=present cache_valid_time=3600
  ignore_errors: "{{ ansible_check_mode }}"
