---
- ansible.builtin.include_role:
    name: apt-key
    apply: { tags: [ always ] }
  vars:
    source: |-
      deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      # deb-src [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    name: "{{ docker_apt_name }}"
    keyname: "{{ docker_apt_key_name }}"
    url: "{{ docker_apt_key_url }}"
    dearmor: "{{ docker_apt_key_dearmor }}"
  tags:
    - apt-key

- name: Install docker
  become: yes
  ansible.builtin.apt:
    pkg:
      - "{{ docker_apt_pkg }}"
      - docker-compose-plugin
    state: present
    cache_valid_time: 3600

# todo configure /etc/docker/daemon.json - "userland-proxy": false
# todo detect/install nvidia-docker2, nvidia-container-toolkit
