---
- ansible.builtin.include_role:
    name: apt-key
    apply: { tags: [ always ] }
  vars:
    source: "deb [arch=amd64] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /"
    name: "{{ nvidia_container_toolkit_apt_name }}"
    keyname: "{{ nvidia_container_toolkit_apt_key_name }}"
    url: "{{ nvidia_container_toolkit_apt_key_url }}"
    dearmor: "{{ nvidia_container_toolkit_apt_key_dearmor }}"
  tags:
    - apt-key

- name: Install nvidia container toolkit
  become: yes
  ansible.builtin.apt: pkg="{{ nvidia_container_toolkit_apt_pkg }}" state=present cache_valid_time=3600
  ignore_errors: "{{ ansible_check_mode }}"

- name: Enable nvidia container runtime
  check_mode: no
  become: yes
  args: { executable: /bin/bash }
  ansible.builtin.shell: |-
    set -e
    val=$(docker system info | grep -i runtime | grep -i nvidia)
    [[ "$val" == "" ]] || exit 0
    echo "ansible_changed=yes"
    [[ "{{ ansible_check_mode }}" != "True" ]] || exit 0
    nvidia-ctk runtime configure --runtime=docker
  notify:
    - reload docker
  register: res
  changed_when: res.stdout is search("ansible_changed=yes")
